module.exports = {
    beforeEach: browser => {
        browser.url("https://alpha.yoodlize.com/")

    },
    after: browser => {
        browser.end()
    },
    'See all': browser => {
        browser
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Tools')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Outdoor Gear')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Electronics')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Party & Wedding')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Recreation')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Clothing')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Home')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Toys')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Lawn')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Sporting')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: DVD')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Venues')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Local')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Experiences')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]')
            .useCss()
            .verify.containsText('.sc-jKVCRD', 'category: Misc')



    },
    'Browse Categories': browser => {
        browser
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[1]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Tools')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[2]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Outdoor')
            .back()
            .pause(3000)
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[3]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Electronics')
            .back()
            .pause(3000)            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[4]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Party')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[5]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Recreational')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[6]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Clothing')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[7]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Home')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[8]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Toys')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[9]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Lawn')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[10]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Sporting')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[11]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: DVD')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[12]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Venues')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[13]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Local')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[14]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Experiences')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[15]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Music')
            .back()
            .pause(3000)            
            .useXpath()
            .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[16]')
            .useCss()
            .pause(2000)
            .verify.containsText('.sc-jKVCRD', 'category: Misc')

    }


}